package com.tokaicom.genbo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Shinsei implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer denpyono;
	private java.lang.String shinsetsumente;
	private java.lang.String kakutockujigyosho;
	private java.lang.String kakutokujigyoshoka;
	private java.lang.String kakutokujigyoshoin;
	private java.lang.String kakutokujigyoshomeishou;
	private java.lang.String kakutokujugyoincode;
	private java.lang.String kakutokujugyoinmeishou;
	private java.lang.String kakutokuyoteinengappi;
	private java.lang.String tourokujigyosho;
	private java.lang.String tourokujigyoshoka;
	private java.lang.String tourokujigyoshoin;
	private java.lang.String tourokujigyoshomeishou;
	private java.lang.String tourokuyoteinengappi;
	private java.lang.String inyoumoushikomishutokubi;
	private java.lang.String touroku;
	private java.lang.String kakutokuuchiwake;
	private java.lang.String bunrui;
	private java.lang.String koumutencode;
	private java.lang.String koumutenmeishou;
	private java.lang.String genbacode;
	private java.lang.String genbameishou;
	private java.lang.String keitai;
	private java.lang.String danchikubun;
	private java.lang.String gasaircon;
	private java.lang.String oneroom;
	private java.lang.String cancelnengappi;

	public Shinsei() {
	}

	public java.lang.Integer getDenpyono() {
		return this.denpyono;
	}

	public void setDenpyono(java.lang.Integer denpyono) {
		this.denpyono = denpyono;
	}

	public java.lang.String getShinsetsumente() {
		return this.shinsetsumente;
	}

	public void setShinsetsumente(java.lang.String shinsetsumente) {
		this.shinsetsumente = shinsetsumente;
	}

	public java.lang.String getKakutockujigyosho() {
		return this.kakutockujigyosho;
	}

	public void setKakutockujigyosho(java.lang.String kakutockujigyosho) {
		this.kakutockujigyosho = kakutockujigyosho;
	}

	public java.lang.String getKakutokujigyoshoka() {
		return this.kakutokujigyoshoka;
	}

	public void setKakutokujigyoshoka(java.lang.String kakutokujigyoshoka) {
		this.kakutokujigyoshoka = kakutokujigyoshoka;
	}

	public java.lang.String getKakutokujigyoshoin() {
		return this.kakutokujigyoshoin;
	}

	public void setKakutokujigyoshoin(java.lang.String kakutokujigyoshoin) {
		this.kakutokujigyoshoin = kakutokujigyoshoin;
	}

	public java.lang.String getKakutokujigyoshomeishou() {
		return this.kakutokujigyoshomeishou;
	}

	public void setKakutokujigyoshomeishou(
			java.lang.String kakutokujigyoshomeishou) {
		this.kakutokujigyoshomeishou = kakutokujigyoshomeishou;
	}

	public java.lang.String getKakutokujugyoincode() {
		return this.kakutokujugyoincode;
	}

	public void setKakutokujugyoincode(java.lang.String kakutokujugyoincode) {
		this.kakutokujugyoincode = kakutokujugyoincode;
	}

	public java.lang.String getKakutokujugyoinmeishou() {
		return this.kakutokujugyoinmeishou;
	}

	public void setKakutokujugyoinmeishou(
			java.lang.String kakutokujugyoinmeishou) {
		this.kakutokujugyoinmeishou = kakutokujugyoinmeishou;
	}

	public java.lang.String getKakutokuyoteinengappi() {
		return this.kakutokuyoteinengappi;
	}

	public void setKakutokuyoteinengappi(java.lang.String kakutokuyoteinengappi) {
		this.kakutokuyoteinengappi = kakutokuyoteinengappi;
	}

	public java.lang.String getTourokujigyosho() {
		return this.tourokujigyosho;
	}

	public void setTourokujigyosho(java.lang.String tourokujigyosho) {
		this.tourokujigyosho = tourokujigyosho;
	}

	public java.lang.String getTourokujigyoshoka() {
		return this.tourokujigyoshoka;
	}

	public void setTourokujigyoshoka(java.lang.String tourokujigyoshoka) {
		this.tourokujigyoshoka = tourokujigyoshoka;
	}

	public java.lang.String getTourokujigyoshoin() {
		return this.tourokujigyoshoin;
	}

	public void setTourokujigyoshoin(java.lang.String tourokujigyoshoin) {
		this.tourokujigyoshoin = tourokujigyoshoin;
	}

	public java.lang.String getTourokujigyoshomeishou() {
		return this.tourokujigyoshomeishou;
	}

	public void setTourokujigyoshomeishou(
			java.lang.String tourokujigyoshomeishou) {
		this.tourokujigyoshomeishou = tourokujigyoshomeishou;
	}

	public java.lang.String getTourokuyoteinengappi() {
		return this.tourokuyoteinengappi;
	}

	public void setTourokuyoteinengappi(java.lang.String tourokuyoteinengappi) {
		this.tourokuyoteinengappi = tourokuyoteinengappi;
	}

	public java.lang.String getInyoumoushikomishutokubi() {
		return this.inyoumoushikomishutokubi;
	}

	public void setInyoumoushikomishutokubi(
			java.lang.String inyoumoushikomishutokubi) {
		this.inyoumoushikomishutokubi = inyoumoushikomishutokubi;
	}

	public java.lang.String getTouroku() {
		return this.touroku;
	}

	public void setTouroku(java.lang.String touroku) {
		this.touroku = touroku;
	}

	public java.lang.String getKakutokuuchiwake() {
		return this.kakutokuuchiwake;
	}

	public void setKakutokuuchiwake(java.lang.String kakutokuuchiwake) {
		this.kakutokuuchiwake = kakutokuuchiwake;
	}

	public java.lang.String getBunrui() {
		return this.bunrui;
	}

	public void setBunrui(java.lang.String bunrui) {
		this.bunrui = bunrui;
	}

	public java.lang.String getKoumutencode() {
		return this.koumutencode;
	}

	public void setKoumutencode(java.lang.String koumutencode) {
		this.koumutencode = koumutencode;
	}

	public java.lang.String getKoumutenmeishou() {
		return this.koumutenmeishou;
	}

	public void setKoumutenmeishou(java.lang.String koumutenmeishou) {
		this.koumutenmeishou = koumutenmeishou;
	}

	public java.lang.String getGenbacode() {
		return this.genbacode;
	}

	public void setGenbacode(java.lang.String genbacode) {
		this.genbacode = genbacode;
	}

	public java.lang.String getGenbameishou() {
		return this.genbameishou;
	}

	public void setGenbameishou(java.lang.String genbameishou) {
		this.genbameishou = genbameishou;
	}

	public java.lang.String getKeitai() {
		return this.keitai;
	}

	public void setKeitai(java.lang.String keitai) {
		this.keitai = keitai;
	}

	public java.lang.String getDanchikubun() {
		return this.danchikubun;
	}

	public void setDanchikubun(java.lang.String danchikubun) {
		this.danchikubun = danchikubun;
	}

	public java.lang.String getGasaircon() {
		return this.gasaircon;
	}

	public void setGasaircon(java.lang.String gasaircon) {
		this.gasaircon = gasaircon;
	}

	public java.lang.String getOneroom() {
		return this.oneroom;
	}

	public void setOneroom(java.lang.String oneroom) {
		this.oneroom = oneroom;
	}

	public java.lang.String getCancelnengappi() {
		return this.cancelnengappi;
	}

	public void setCancelnengappi(java.lang.String cancelnengappi) {
		this.cancelnengappi = cancelnengappi;
	}

	public Shinsei(java.lang.Integer denpyono, java.lang.String shinsetsumente,
			java.lang.String kakutockujigyosho,
			java.lang.String kakutokujigyoshoka,
			java.lang.String kakutokujigyoshoin,
			java.lang.String kakutokujigyoshomeishou,
			java.lang.String kakutokujugyoincode,
			java.lang.String kakutokujugyoinmeishou,
			java.lang.String kakutokuyoteinengappi,
			java.lang.String tourokujigyosho,
			java.lang.String tourokujigyoshoka,
			java.lang.String tourokujigyoshoin,
			java.lang.String tourokujigyoshomeishou,
			java.lang.String tourokuyoteinengappi,
			java.lang.String inyoumoushikomishutokubi,
			java.lang.String touroku, java.lang.String kakutokuuchiwake,
			java.lang.String bunrui, java.lang.String koumutencode,
			java.lang.String koumutenmeishou, java.lang.String genbacode,
			java.lang.String genbameishou, java.lang.String keitai,
			java.lang.String danchikubun, java.lang.String gasaircon,
			java.lang.String oneroom, java.lang.String cancelnengappi) {
		this.denpyono = denpyono;
		this.shinsetsumente = shinsetsumente;
		this.kakutockujigyosho = kakutockujigyosho;
		this.kakutokujigyoshoka = kakutokujigyoshoka;
		this.kakutokujigyoshoin = kakutokujigyoshoin;
		this.kakutokujigyoshomeishou = kakutokujigyoshomeishou;
		this.kakutokujugyoincode = kakutokujugyoincode;
		this.kakutokujugyoinmeishou = kakutokujugyoinmeishou;
		this.kakutokuyoteinengappi = kakutokuyoteinengappi;
		this.tourokujigyosho = tourokujigyosho;
		this.tourokujigyoshoka = tourokujigyoshoka;
		this.tourokujigyoshoin = tourokujigyoshoin;
		this.tourokujigyoshomeishou = tourokujigyoshomeishou;
		this.tourokuyoteinengappi = tourokuyoteinengappi;
		this.inyoumoushikomishutokubi = inyoumoushikomishutokubi;
		this.touroku = touroku;
		this.kakutokuuchiwake = kakutokuuchiwake;
		this.bunrui = bunrui;
		this.koumutencode = koumutencode;
		this.koumutenmeishou = koumutenmeishou;
		this.genbacode = genbacode;
		this.genbameishou = genbameishou;
		this.keitai = keitai;
		this.danchikubun = danchikubun;
		this.gasaircon = gasaircon;
		this.oneroom = oneroom;
		this.cancelnengappi = cancelnengappi;
	}

}